version: '2'

networks:
  default:
    driver: bridge

services:
  server:
    container_name: server&front
    build: GGHB/

  mysql:
    container_name: bd
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /var/lib/docker/volumes/bd:/var/lib/mysql
