version: '2'

networks:
  default:
    driver: bridge

services:
  server:
    container_name: serverNFront
    build: GGHB/

  mysql:
    container_name: bd
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
