version: '2'

networks:
  default:
    driver: bridge

services:
  mysql_gghb:
    container_name: bd_gghb
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    volumes:
      - ./GGHB/BD:/docker-entrypoint-initdb.d

  server_gghb:
    container_name: serverNFront_gghb
    build: GGHB/
    ports:
      - 8080:8080
